version: "3.7"

services:
  jupyter:
    image: jupyter/base-notebook:latest
    restart: unless-stopped
    environment:
      - JUPYTER_TOKEN=umbrel
    ports:
      - "8888:8888"
    volumes:
      - jupyter-data:/home/jovyan/work

volumes:
  jupyter-data:
